from .audioTask import AudioTask
from .cr2Task import Cr2Task
from .dayPageTask import DayPageTask
from .galleryTask import GalleryTask
from .geojsonTask import GeojsonTask
from .gpxTask import GPXTask
from .imageTask import ImageTask
from .journalTask import JournalTask
from .markdownTask import MarkdownTask
from .qstarzTask import QstarzTask
from .siteTask import SiteTask
from .tagsTask import TagsTask
from .textTask import TextTask
