# Logging configuration
version: 1
formatters:
  terminal:
    format: '%(levelname)-5s %(relativeCreated)6dms %(fmt_icon)s%(message)s'
    defaults:
      icon: '   '
      fmt_icon: '   '
  log:
    format: '%(asctime)s: %(name)s, %(task)s [%(levelname)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: terminal
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: log
    filename: None  # Set this to your desired log file path
    mode: "w"
loggers:
  mkmapdiary:
    level: DEBUG
root:
  level: INFO
  handlers: [console, file]
