use_directory_urls: False
strict: True

theme:
  name: material
  icon:
    logo: "material/plane-train"

plugins:
  - search
  - offline
  - glightbox:
      skip_classes:
        - skip-lightbox

exclude_docs: |
  /assets/*.md

markdown_extensions: 
  - pymdownx.snippets:
      check_paths: True
  - attr_list
  - md_in_html
  - pymdownx.blocks.html
  - pymdownx.blocks.admonition
  - pymdownx.superfences

extra_css:
  - extra.css
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.css
  - https://unpkg.com/leaflet.markercluster@1.0.3/dist/MarkerCluster.css
  - https://unpkg.com/@lychee-org/leaflet.photo@1.0.0/Leaflet.Photo.css

extra_javascript:
  - path: https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
  - path: https://unpkg.com/leaflet.markercluster@1.0.3/dist/leaflet.markercluster.js
  - path: https://unpkg.com/@lychee-org/leaflet.photo@1.0.0/Leaflet.Photo.js
  - path: extra.js